name: App CI / Tests before main merge

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Compile JavaScript code
        run: npx tsc
      - name: Test production and dev app in docker container
        run: docker compose -f docker-compose.test.yml run --rm app-test-run
